### ISSUE TITLE
Packaging issue - Potential typo

### ISSUE THREAD

**Issue by PuddlePumpkin** [zeplin455/TwitchInteractionUE#1]
`[512]UATHelper: Packaging (Windows): ERROR: Expecting to find a type to be declared in a module rules named 'HttpServer' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.I` ran into this issue packaging for windows in a test project, I managed to package by changing `HttpServer` in TwitchInteraction.Build.cs to `HTTPServer` however was unsure if this could create any issues since the unreal documentation seems to list the module as lowercase HttpServer. ❤️

**Comment by zeplin455** [comment]
Hello,
Are you running this on the latest version of UE5 or still the early access version?
I haven't updated this for the latest version yet but will update it and fix the issue.

The intension is to use the Unreal Engine internal http server class as a helper for authentication so if it is misnamed somehow and you changed it then it should be fine. Its just built around a simple trick to have a redirect from a website go to your machine to grab the authentication info it intends to deliver.

**Comment by zeplin455** [comment]
It was indeed a typo, fixed it. Thank you :)
